# Welcome to Jekyll!


# Site settings

title: Brent's Blog
email:
description:


# Url Stuffs
baseurl: "/blog" # the subpath of your site, e.g. /blog
production_url : http://sgtphips.github.io.com
url: ""
permalink: /:categories/:title/

# Extra Stuff <- Probably should go in a data file
github_username:  sgtphips

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
